'use client';
import "./globals.css";
import { RecoilRoot } from "recoil";


// Had to remove for use client to work.
// export const metadata: Metadata = {
//   title: "AI Interviewer",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilRoot>
      <html lang="en">
        <body>{children}</body>
      </html>
    </RecoilRoot>
  );
}
